### ISSUE TITLE
Image resizing operation

### ISSUE THREAD

**Issue by jayendra13** [deepmind/dm_pix#28]
Is there any specific reason not to include the resize operation ?

https://www.tensorflow.org/api_docs/python/tf/image/resize

There is a interpolation module in the code and would it be useful for this `tf.image.resize` operation ?

**Comment by claudiofantacci** [comment]
Hi @jayendra13, the `resize` operation is implemented in JAX, in the `jax.image` module!
You can find the documentation [here](https://jax.readthedocs.io/en/latest/_autosummary/jax.image.resize.html) and its implementation [here](https://github.com/google/jax/blob/main/jax/_src/image/scale.py#L273) (and a few other functions).

**Comment by jayendra13** [comment]
Thanks @claudiofantacci pointing it out 👍
